meta_product_name: "Sandrine Rousset"
meta_title: "Sandrine Rousset, artiste peintre et sculptrice"
meta_description: "Découvrez les oeuvres (peintures et sculptures) réalisées par Sandrine Rousset"
meta_image: "cover.jpg" # should exist in `app/assets/images/`

